services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_travel_service
    ports:
      - "8001:80"  # Porta externa 8001 mapeada para 80 interna
    volumes:
      - .:/var/www/html
      - ./apache-config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - travel_service_network
    depends_on:
      - mysql

  # Serviço MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_travel_service
    environment:
      MYSQL_DATABASE: travel_service_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"  # Porta padrão do MySQL
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - travel_service_network

networks:
  travel_service_network:

volumes:
  mysqldata: