version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_modelo
    ports:
      - "8001:80"  # Altere a porta externa para 8080
    volumes:
      - .:/var/www/html
      - ./apache-config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - modelo_network
    depends_on:
      - postgres

  # Serviço PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres_modelo
    environment:
      POSTGRES_DB: modelo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - modelo_network

networks:
  modelo_network:

volumes:
  pgdata:
